routes/web.php
<?php

use App\Http\Controllers\FizBusController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\KontrakController;
use App\Http\Controllers\PegawaiController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('admin.layout.master');
});

Route::get('test-2',[FizBusController::class,'index'])->name('fizBus');


Route::prefix('admin')->group(function () {
    Route::resource('pegawai',PegawaiController::class);
    Route::resource('jabatan',JabatanController::class)->except('show');
    Route::resource('kontrak',KontrakController::class)->except('show');
});

app/Http/Controllers/JabatanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\JabatanPegawai;
use App\Http\Requests\JabatanStoreRequest;
use App\Http\Requests\JabatanUpdateRequest;

class JabatanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        $jabatans = JabatanPegawai::all();
        return view('admin.pages.jabatan.index',compact('jabatans'));

    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('admin.pages.jabatan.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(JabatanStoreRequest $request )
    {
        //
        $data = $request->safe()->all();
        $jabatan = new JabatanPegawai($data);
        $jabatan->save();

        return redirect()->route('jabatan.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(JabatanPegawai $jabatan)
    {
        //
        return view('admin.pages.jabatan.edit', compact('jabatan'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(JabatanUpdateRequest $request,JabatanPegawai  $jabatan)
    {
        //
        $jabatan->update($request->all());
        return redirect()->route('jabatan.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(JabatanPegawai $jabatan)
    {
        //
        $jabatan->delete();
        return redirect()->route('jabatan.index');
    }
}

resources/views/admin/pages/jabatan/create.blade.php
@extends('admin.layout.master')
@section('main')
@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('pegawai.index') }}">Jabatan</a></li>
<li class="breadcrumb-item active">Tambah Data Jabatan</li>
@endsection
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Form Tambah Data Jabatan</h5>

      <!-- General Form Elements -->
      <form action="{{ route('jabatan.store') }}" method="POST">
        @csrf
        <div class="row mb-3">
          <label for="inputText" class="col-sm-2 col-form-label">Nama Jabatan</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" name="nama_jabatan">
          </div>
        </div>
        <div class="row mb-3">
            <label for="inputText" class="col-sm-2 col-form-label">Kode Jabatan</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="kode_jabatan">
            </div>
          </div>
        <div class="text-center">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Simpan Jabatan</button>
          </div>
        </div>

      </form><!-- End General Form Elements -->

    </div>
</div>
@endsection

resources/views/admin/pages/jabatan/edit.blade.php
@extends('admin.layout.master')
@section('main')
@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('pegawai.index') }}">Jabatan</a></li>
<li class="breadcrumb-item active">Edit Data Jabatan</li>
@endsection
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Form Edit Data Jabatan</h5>

      <!-- General Form Elements -->
      <form action="{{ route('jabatan.update',$jabatan) }}" method="POST">
        @csrf @method('PUT')
        <div class="row mb-3">
          <label for="inputText" class="col-sm-2 col-form-label">Nama Jabatan</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" name="nama_jabatan" value="{{ $jabatan->nama_jabatan }}">
          </div>
        </div>
        <div class="row mb-3">
            <label for="inputText" class="col-sm-2 col-form-label">Kode Jabatan</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="kode_jabatan"  value="{{ $jabatan->nama_jabatan }}">
            </div>
          </div>
        <div class="text-center">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Simpan Jabatan</button>
          </div>
        </div>

      </form><!-- End General Form Elements -->

    </div>
</div>
@endsection

resources/views/admin/pages/jabatan/index.blade.php
@extends('admin.layout.master')
@section('main')
@section('breadcrumb')
<li class="breadcrumb-item active">Jabatan</li>
@endsection
<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Tabel Data Jabatan</h5>
                    <div style="float: left; margin-bottom: 10px">
                        <a href="{{ route('jabatan.create') }}">
                            <button type="button" class="btn btn-primary"><i class="bi bi-clipboard2-plus"></i>Tambah
                                Jabatan</button>
                        </a>
                    </div>
                    <!-- Table with stripped rows -->
                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th scope="col">No</th>
                                <th scope="col">Nama Jabatan</th>
                                <th scope="col">Kode Jabatan</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        @php
                        $no = 1;
                        @endphp
                        <tbody>
                            @forelse ( $jabatans as $jabatan )
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $jabatan->nama_jabatan }}</td>
                                <td>{{ $jabatan->kode_jabatan }}</td>
                                <td>
                                    <a href="{{ route('jabatan.edit',$jabatan) }}">
                                        <button type="button" class="btn btn-warning"><i
                                                class="bi bi-pencil"></i></button>
                                    </a>
                                    <button type="button" class="btn btn-danger delete-btn" data-toggle="modal" data-target="#exampleModal">
                                        <i class="bi bi-trash"></i>
                                    </div>
                                </td>
                            </tr>
                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                              <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-body">
                                    Apakah Anda yakin Ingin Menghapus data ini ?
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <form action="{{ route('jabatan.destroy',$jabatan) }}" method="POST">
                                        @csrf @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Hapus Data</button>
                                    </form>
                                  </div>
                                </div>
                              </div>
                            </div>
                            @empty

                            @endforelse

                        </tbody>
                    </table>
                    <!-- End Table with stripped rows -->

                </div>
            </div>

        </div>
</section>
</div>
@endsection