routes/web.php
<?php

use App\Http\Controllers\FizBusController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\KontrakController;
use App\Http\Controllers\PegawaiController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('admin.layout.master');
});

Route::get('test-2',[FizBusController::class,'index'])->name('fizBus');


Route::prefix('admin')->group(function () {
    Route::resource('pegawai',PegawaiController::class);
    Route::resource('jabatan',JabatanController::class)->except('show');
    Route::resource('kontrak',KontrakController::class)->except('show');
});

app/Models/Kontrak.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kontrak extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama_kontrak',
        'tgl_mulai',
        'tgl_selesai'
    ];
}

app/Http/Controllers/KontrakController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kontrak;
use App\Http\Requests\KontrakStoreRequest;
use App\Http\Requests\KontrakUpdateRequest;

class KontrakController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $kontraks = Kontrak::all();
        return view('admin.pages.kontrak.index',compact('kontraks'));
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('admin.pages.kontrak.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(KontrakStoreRequest $request, Kontrak $kontrak)
    {
        //
        $data = $request->safe()->all();
        $kontrak = new Kontrak($data);
        $kontrak->save();

        return redirect()->route('kontrak.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Kontrak $kontrak)
    {
        //
        return view('admin.pages.kontrak.edit',compact('kontrak'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(KontrakUpdateRequest $request,Kontrak  $kontrak)
    {
        //
        $kontrak->update($request->all());
        return redirect()->route('kontrak.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Kontrak $kontrak)
    {
        //
        $kontrak->delete();
        return redirect()->route('kontrak.index');
    }
}

resources/views/admin/pages/kontrak/create.blade.php
@extends('admin.layout.master')
@section('main')
@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('pegawai.index') }}">Kontrak</a></li>
<li class="breadcrumb-item active">Tambah Data Kontrak</li>
@endsection
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Form Tambah Data Kontrak</h5>

      <!-- General Form Elements -->
      <form action="{{ route('kontrak.store') }}" method="POST">
        @csrf
        <div class="row mb-3">
          <label for="inputText" class="col-sm-2 col-form-label">Nama Kontrak</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" name="nama_kontrak">
          </div>
        </div>
        <div class="row mb-3">
            <label for="inputText" class="col-sm-2 col-form-label">Tanggal Mulai Kontrak</label>
            <div class="col-sm-10">
              <input type="date" class="form-control" name="tgl_mulai">
            </div>
          </div>
          <div class="row mb-3">
            <label for="inputText" class="col-sm-2 col-form-label">Tanggal Selesai Kontrak</label>
            <div class="col-sm-10">
              <input type="date" class="form-control" name="tgl_selesai">
            </div>
          </div>
        <div class="text-center">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Simpan Kontrak</button>
          </div>
        </div>

      </form><!-- End General Form Elements -->

    </div>
</div>
@endsection

resources/views/admin/pages/kontrak/edit.blade.php
@extends('admin.layout.master')
@section('main')
@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('kontrak.index') }}">Kontrak</a></li>
<li class="breadcrumb-item active">Edit Data Kontrak</li>
@endsection
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Form Edit Data Kontrak</h5>

      <!-- General Form Elements -->
      <form action="{{ route('kontrak.update',$kontrak) }}" method="POST">
        @csrf @method("PUT")
        <div class="row mb-3">
          <label for="inputText" class="col-sm-2 col-form-label">Nama Kontrak</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" name="nama_kontrak" value="{{ $kontrak->nama_kontrak }}">
          </div>
        </div>
        <div class="row mb-3">
            <label for="inputText" class="col-sm-2 col-form-label">Tanggal Mulai Kontrak</label>
            <div class="col-sm-10">
              <input type="date" class="form-control" name="tgl_mulai" value="{{ $kontrak->tgl_mulai }}">
            </div>
          </div>
          <div class="row mb-3">
            <label for="inputText" class="col-sm-2 col-form-label">Tanggal Selesai Kontrak</label>
            <div class="col-sm-10">
              <input type="date" class="form-control" name="tgl_selesai" value="{{ $kontrak->tgl_selesai }}">
            </div>
          </div>
        <div class="text-center">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update Kontrak</button>
          </div>
        </div>

      </form><!-- End General Form Elements -->

    </div>
</div>
@endsection

resources/views/admin/pages/kontrak/index.blade.php
@extends('admin.layout.master')
@section('main')
@section('breadcrumb')
<li class="breadcrumb-item active">Kontrak</li>
@endsection
<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Tabel Data Kontrak</h5>
                    <div style="float: left; margin-bottom: 10px">
                        <a href="{{ route('kontrak.create') }}">
                            <button type="button" class="btn btn-primary"><i class="bi bi-clipboard2-plus"></i>Tambah
                                Kontrak</button>
                        </a>
                    </div>
                    <!-- Table with stripped rows -->
                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th scope="col">No</th>
                                <th scope="col">Nama Kontrak</th>
                                <th scope="col">Tanggal Mulai</th>
                                <th scope="col">Tanggal Selesai</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        @php
                        $no = 1;
                        @endphp
                        <tbody>
                            @forelse ( $kontraks as $kontrak )
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $kontrak->nama_kontrak }}</td>
                                <td>{{ $kontrak->tgl_mulai }}</td>
                                <td>{{ $kontrak->tgl_selesai }}</td>
                                <td>
                                    <a href="{{ route('kontrak.edit',$kontrak) }}">
                                        <button type="button" class="btn btn-warning"><i
                                                class="bi bi-pencil"></i></button>
                                    </a>
                                    <button type="button" class="btn btn-danger delete-btn" data-toggle="modal" data-target="#exampleModal">
                                        <i class="bi bi-trash"></i>
                                    </button>
                                    </div>
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                      <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                          <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                              <span aria-hidden="true">&times;</span>
                                            </button>
                                          </div>
                                          <div class="modal-body">
                                            Apakah Anda yakin Ingin Menghapus data ini ?
                                          </div>
                                          <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <form action="{{ route('kontrak.destroy',$kontrak) }}" method="POST">
                                                @csrf @method('DELETE')
                                                <button type="submit" class="btn btn-danger">Hapus Data</button>
                                            </form>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                </div>
                                </td>
                            </tr>
                            @empty

                            @endforelse

                        </tbody>
                    </table>
                    <!-- End Table with stripped rows -->

                </div>
            </div>

        </div>
</section>
</div>
@endsection