routes/web.php
<?php

use App\Http\Controllers\FizBusController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\KontrakController;
use App\Http\Controllers\PegawaiController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('admin.layout.master');
});

Route::get('test-2',[FizBusController::class,'index'])->name('fizBus');


Route::prefix('admin')->group(function () {
    Route::resource('pegawai',PegawaiController::class);
    Route::resource('jabatan',JabatanController::class)->except('show');
    Route::resource('kontrak',KontrakController::class)->except('show');
});

resources/views/admin/pages/pagawai/create.blade.php
@extends('admin.layout.master')
@section('main')
@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('pegawai.index') }}">Pegawai</a></li>
<li class="breadcrumb-item active">Tambah Data pegawai</li>
@endsection
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Form Tambah Data pegawai</h5>

      <!-- General Form Elements -->
      <form action="{{ route('pegawai.store') }}" method="POST">
        @csrf
        <div class="row mb-3">
          <label for="inputText" class="col-sm-2 col-form-label">Nama Pegawai</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" name="nama_pegawai">
          </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Jabatan</label>
            <div class="col-sm-10">
              <select class="form-select" name="id_jabatan" aria-label="Default select example">
                <option selected>Open this select menu</option>
                @foreach ($jabatans as $jabatan)
                <option value="{{ $jabatan->id }}">{{ $jabatan->nama_jabatan }}</option>
                @endforeach
              </select>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Jenis Kontrak</label>
            <div class="col-sm-10">
              <select class="form-select" name="id_kontrak" aria-label="Default select example">
                <option selected>Open this select menu</option>
                @foreach ($kontraks as $kontrak)
                <option value="{{ $kontrak->id }}">{{ $kontrak->nama_kontrak }}</option>
                @endforeach
              </select>
            </div>
          </div>
          <div class="row mb-3">
            <label for="inputText" class="col-sm-2 col-form-label">Tanggal Lahir</label>
            <div class="col-sm-10">
              <input type="date" class="form-control" name="tgl_lahir">
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Jenis Kelamin</label>
            <div class="col-sm-10">
              <select class="form-select" name="jenis_kelamin" aria-label="Default select example">
                <option selected>Open this select menu</option>
                <option value="Laki-Laki">Laki-Laki</option>
                <option value="Perempuan">Perempuan</option>
              </select>
            </div>
          </div>
          <div class="row mb-3">
            <label for="inputText" class="col-sm-2 col-form-label">Agama</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="agama">
            </div>
          </div>
        <div class="text-center">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Simpan Kontrak</button>
          </div>
        </div>

      </form><!-- End General Form Elements -->

    </div>
</div>
@endsection

resources/views/admin/pages/pagawai/edit.blade.php
@extends('admin.layout.master')
@section('main')
@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('pegawai.index') }}">Pegawai</a></li>
<li class="breadcrumb-item active">Edit Data Pegawai</li>
@endsection
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Form Edit Data Kontrak</h5>

      <!-- General Form Elements -->
      <form action="{{ route('pegawai.update',$pegawai) }}" method="POST">
        @csrf @method('PUT')
        <div class="row mb-3">
          <label for="inputText" class="col-sm-2 col-form-label">Nama Pegawai</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" name="nama_pegawai" value="{{ $pegawai->nama_pegawai }}">
          </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Jabatan</label>
            <div class="col-sm-10">
              <select class="form-select" name="id_jabatan" aria-label="Default select example">
                <option selected value="{{ $pegawai->id_jabatan }}">{{ $pegawai->jabatans->nama_jabatan }}</option>
                @foreach ($jabatans as $jabatan)
                <option value="{{ $jabatan->id }}">{{ $jabatan->nama_jabatan }}</option>
                @endforeach
              </select>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Jenis Kontrak</label>
            <div class="col-sm-10">
              <select class="form-select" name="id_kontrak" aria-label="Default select example">
                <option selected value="{{ $pegawai->id_kontrak }}">{{ $pegawai->kontraks->nama_kontrak }}</option>
                @foreach ($kontraks as $kontrak)
                <option value="{{ $kontrak->id }}">{{ $kontrak->nama_kontrak }}</option>
                @endforeach
              </select>
            </div>
          </div>
          <div class="row mb-3">
            <label for="inputText" class="col-sm-2 col-form-label">Tanggal Lahir</label>
            <div class="col-sm-10">
              <input type="date" class="form-control" name="tgl_lahir" value="{{ $pegawai->tgl_lahir }}">
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Jenis Kelamin</label>
            <div class="col-sm-10">
              <select class="form-select" name="jenis_kelamin" aria-label="Default select example">
                <option selected value="{{ $pegawai->jenis_kelamin }}">{{ $pegawai->jenis_kelamin }}</option>
                <option value="Laki-Laki">Laki-Laki</option>
                <option value="Perempuan">Perempuan</option>
              </select>
            </div>
          </div>
          <div class="row mb-3">
            <label for="inputText" class="col-sm-2 col-form-label">Agama</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="agama" value="{{ $pegawai->agama }}">
            </div>
          </div>
        <div class="text-center">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update Pegawai</button>
          </div>
        </div>

      </form><!-- End General Form Elements -->

    </div>
</div>
@endsection

resources/views/admin/pages/pagawai/index.blade.php
@extends('admin.layout.master')
@section('main')
@section('breadcrumb')
<li class="breadcrumb-item active">Pagawai</li>
@endsection
    <section class="section">
        <div class="row">
          <div class="col-lg-12">

            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Tabel Data Pegawai</h5>
                <div style="float: left; margin-bottom: 10px">
                    <a href="{{ route('pegawai.create') }}">
                        <button type="button" class="btn btn-primary"><i class="bi bi-clipboard2-plus"></i>Tambah Pegawai</button>
                    </a>
                  </div>
                <!-- Table with stripped rows -->
                <table id="example" class="table table-striped table-bordered" style="width:100%">
                  <thead>
                    <tr>
                      <th scope="col">No</th>
                      <th scope="col">Nama</th>
                      <th scope="col">Jabatan</th>
                      <th scope="col">Tanggal Kontrak</th>
                      <th scope="col">Tanggal Lahir</th>
                      <th scope="col">Jenis Kelamin</th>
                      <th scope="col">Agama</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  @php
                      $no = 1;
                  @endphp
                  <tbody>
                    @forelse ( $pegawais as $pegawai )
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>{{ $pegawai->nama_pegawai }}</td>
                        <td>{{ $pegawai->jabatans->nama_jabatan }}</td>
                        <td>{{ $pegawai->kontraks->nama_kontrak }}</td>
                        <td>{{ $pegawai->tgl_lahir }}</td>
                        <td>{{ $pegawai->jenis_kelamin }}</td>
                        <td>{{ $pegawai->agama }}</td>
                        <td>
                            <a href="{{ route('pegawai.edit',$pegawai) }}">
                                <button type="button" class="btn btn-warning"><i
                                        class="bi bi-pencil"></i></button>
                            </a>
                            <button type="button" class="btn btn-danger delete-btn" data-toggle="modal" data-target="#exampleModal">
                                <i class="bi bi-trash"></i>
                            </div>
                        </td>
                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                <div class="modal-body">
                                  Apakah Anda yakin Ingin Menghapus data ini ?
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                  <form action="{{ route('pegawai.destroy',$pegawai) }}" method="POST">
                                      @csrf @method('DELETE')
                                      <button type="submit" class="btn btn-danger">Hapus Data</button>
                                  </form>
                                </div>
                              </div>
                            </div>
                          </div>
                    </tr>
                    @empty

                    @endforelse

                  </tbody>
                </table>
                <!-- End Table with stripped rows -->

              </div>
            </div>

          </div>
      </section>
</div>
@endsection